{
 "title": "Coder Control Plane",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`} == 1) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "(count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`} == 0) or vector(0)) > 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "One or more replicas are required to be running in order to serve the control-plane.\n\nSee [High Availability](https://coder.com/docs/v2/latest/admin/high-availability) for details on how to\nrun multiple `coderd` replicas."
   }
  },
  {
   "title": "Enterprise License",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(coderd_license_user_limit_enabled)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "(\n  max(coderd_license_active_users) / max(coderd_license_limit_users)\n) > 0",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "If you would like to try Coder's [Enterprise features](https://coder.com/docs/v2/latest/enterprise), you can [request a trial license](https://coder.com/docs/v2/latest/faqs#how-do-i-add-an-enterprise-license)."
   }
  },
  {
   "title": "CPU Usage Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`, resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`, resource=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": {
    "content": "The cumulative CPU used per core-second. If `coderd` was using a full CPU core, that would be represented as 1 second.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "Terminations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (\n  count_over_time(kube_pod_container_status_terminated_reason{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`}[$__interval])\n)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": {
    "content": "Pods can be terminated for several reasons:\n- `OOMKilled`: pod exceeded its defined memory limit or was terminated by the OS for using excessive memory (if no limit defined)\n- `Error`: usually attributeable to a configuration problem\n- `Evicted`: pod has been evicted from node for overusing resources and will be rescheduled on another node is possible"
   }
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`, resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`, resource=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "options": {
    "content": "This shows the total memory used by each `coderd` container; it is the same metric which the [OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) uses.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "Pubsub Latency (Median)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, coder_pubsub_send_latency_seconds)",
     "legendFormat": "Send"
    },
    {
     "expr": "quantile(0.5, coder_pubsub_receive_latency_seconds)",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Pubsub Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(coder_pubsub_latency_measure_errs_total[$__range]))\n  / count(coder_pubsub_latency_measure_errs_total)\n) or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "options": {
    "content": "`coderd` uses Postgres for passing messages between subcomponents for coordination and signalling;\nthis is called \"pubsub\" (or publish-subscribe).\n\nWe measure the time for messages to be sent and received. Latencies higher than 500ms will likely lead to\nyour Coder deployment feeling sluggish. High latency is usually an indication that your Postgres server is under-resourced on CPU.\n\nHigh values for median should be concerning,\nwhile the 90th percentile shows the outliers."
   }
  },
  {
   "title": "Pubsub Latency (P90)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.9, coder_pubsub_send_latency_seconds)",
     "legendFormat": "Send"
    },
    {
     "expr": "quantile(0.9, coder_pubsub_receive_latency_seconds)",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(coderd_api_requests_processed_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "options": {
    "content": "This shows the number of requests per second each `coderd` replica is handling.\n\nHeavy skewing towards a single `coderd` replica indicates faulty loadbalancing."
   }
  }
 ]
}
{
 "title": "Coder Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coder Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`} == 1) or vector(0) > 0",
     "legendFormat": "Up"
    },
    {
     "expr": "count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`} == 0) or vector(0) > 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Provisioners",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`})",
     "legendFormat": "Built-in"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder-provisioner.*`, namespace=`coder`})",
     "legendFormat": "External"
    }
   ]
  },
  {
   "title": "Workspace Builds",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (coderd_workspace_latest_build_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Running Workspaces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", namespace=`coder-workspaces`} == 1)\nor\nsum(max by (workspace_owner, template_name, template_version) (coderd_workspace_latest_build_status{status=\"succeeded\", workspace_transition=\"start\"}))\nor\nvector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage High Watermark (Cumulative)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`}[1h:1m])\n        [$__range:]\n    )\n)",
     "legendFormat": "Control Plane CPU"
    },
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{pod=~`coder-provisioner.*`, namespace=`coder`}[1h:1m])\n        [$__range:]\n    )\n)",
     "legendFormat": "Provisioner CPU"
    },
    {
     "expr": "sum(\n    max_over_time(\n        container_memory_working_set_bytes{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`coder`}\n        [$__range:]\n    )\n)",
     "legendFormat": "Control Plane RAM"
    },
    {
     "expr": "sum(\n    max_over_time(\n        container_memory_working_set_bytes{pod=~`coder-provisioner.*`, namespace=`coder`}\n        [$__range:]\n    )\n)",
     "legendFormat": "Provisioner RAM"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(coderd_db_tx_duration_seconds_count[5m])) > bool 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Observability Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"kps-kube-prometheus-stack-prometheus\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"loki\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"promtail\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Coder Prebuilds",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "template",
    "label": "Template",
    "query": {
     "query": "label_values(coderd_prebuilt_workspaces_desired,template_name)"
    }
   },
   {
    "name": "preset",
    "label": "Preset",
    "query": {
     "query": "label_values(coderd_prebuilt_workspaces_desired{template_name=~\"$template\"},preset_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current: Global",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_desired) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_running) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_eligible) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "All Time: Global",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_created_total)) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_failed_total)) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_claimed_total)) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  { "title": "$preset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "preset" },
  {
   "title": "All Time: $preset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_created_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_failed_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_claimed_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "Pool Operations: $preset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_created_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_failed_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_claimed_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "Pool Capacity: $preset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_desired{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_running{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_eligible{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "Current: $preset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_desired{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_running{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_eligible{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "All Time: Regular vs Prebuilt",
   "type": "stat",
   "description": "Compares the total number of regular workspace creations to prebuilt workspace claims to date.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (template_name, preset_name) (\n  coderd_workspace_creation_total{\n    template_name=~\"$template\", preset_name=~\"$preset\"\n  }\n)) or vector(0)",
     "legendFormat": "Regular workspaces created"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (\n  coderd_prebuilt_workspaces_claimed_total{\n    template_name=~\"$template\", preset_name=~\"$preset\"\n  }\n)) or vector(0)\n",
     "legendFormat": "Prebuilt workspaces claimed"
    }
   ]
  },
  {
   "title": "Workspace Build Latency p50",
   "type": "timeseries",
   "description": "Median (p50) build time in seconds for Regular Workspace Creation, Prebuilt Workspace Creation, and Prebuilt Workspace Claim",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"regular\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Regular Creation"
    },
    {
     "expr": "histogram_quantile(0.5,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"prebuild\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Creation"
    },
    {
     "expr": "histogram_quantile(0.5,\n  sum(\n    coderd_prebuilt_workspace_claim_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Claim"
    }
   ]
  },
  {
   "title": "Workspace Build Latency p95",
   "type": "timeseries",
   "description": "95th-percentile (p95) build time in seconds for Regular Workspace Creation, Prebuilt Workspace Creation, and Prebuilt Workspace Claim.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"regular\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Regular Creation"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"prebuild\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Creation"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    coderd_prebuilt_workspace_claim_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Claim"
    }
   ]
  },
  {
   "title": "All Time: Prebuilds Usage %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  100 *\n  (\n    sum(\n      coderd_prebuilt_workspaces_claimed_total{\n        template_name=\"$template\", preset_name=\"$preset\"\n      }\n    ) or vector(0)\n  )\n  /\n  clamp_min(\n    ( \n      sum(\n        coderd_prebuilt_workspaces_claimed_total{\n          template_name=\"$template\", preset_name=\"$preset\"\n        }\n      ) or vector(0))\n    +\n    (\n      sum(\n        coderd_workspace_creation_total{\n          template_name=\"$template\", preset_name=\"$preset\"\n        }\n      ) or vector(0)),\n    1\n  ),\n  100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Coder Provisioners",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Provisioners",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder.*`, pod!~`.*provisioner.*`})",
     "legendFormat": "Built-in"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder-provisioner.*`, namespace=`coder`})",
     "legendFormat": "External"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "Provisioners are responsible for building workspaces.\n\n`coderd` runs built-in provisioners by default. Control this with the `CODER_PROVISIONER_DAEMONS` environment variable or `--provisioner-daemons` flag.\n\nYou can also consider [External Provisioners](https://coder.com/docs/v2/latest/admin/provisioners). Running both built-in and external provisioners is perfectly valid,\nalthough dedicated (external) provisioners will generally give the best build performance."
   }
  },
  {
   "title": "Builds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(coderd_provisionerd_jobs_current) > 0) or vector(0)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons)",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "The maximum number of simultaneous builds is equivalent to the number of `provisionerd` daemons running.\n\nThe \"Capacity\" panel shows the how many simultaneous builds are possible."
   }
  },
  {
   "title": "Build Times",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(coderd_provisionerd_job_timings_seconds_bucket[$__range])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(coderd_provisionerd_job_timings_seconds_bucket[$__range])))",
     "legendFormat": "90th Percentile"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": {
    "content": "This shows the median and 90th percentile workspace build times.\n\nLong build times can impede developers' productivity while they wait for workspaces to start or be created."
   }
  },
  {
   "title": "Build Count Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(coderd_provisionerd_job_timings_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "_NOTE: this will not show the current hour._"
   }
  },
  {
   "title": "CPU Usage Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~`coder-provisioner.*`, namespace=`coder`}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "options": {
    "content": "The cumulative CPU used per core-second. If the process was using a full CPU core, that would be represented as 1 second.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{pod=~`coder-provisioner.*`, namespace=`coder`})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder-provisioner.*`, namespace=`coder`, resource=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": {
    "content": "This shows the total memory used by each container; it is the same metric which the [OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) uses.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=~`(coder|coder)`, logger=~\"(.*runner|terraform|provisioner.*)\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "options": {
    "content": "This panel shows all logs across built-in and [external provisioners](https://coder.com/docs/v2/latest/admin/provisioners)."
   }
  }
 ]
}
{
 "title": "Coder Workspaces",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "workspace_name",
    "label": "Workspace Name Filter",
    "query": {
     "query": "label_values(coderd_workspace_builds_total,workspace_name)"
    }
   },
   {
    "name": "template_name",
    "label": "Template Name Filter",
    "query": {
     "query": "label_values(coderd_workspace_builds_total,template_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<small>**HINT**: use the dropdowns above to filter by specific workspaces and/or templates.</small>"
   }
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1.2 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 2.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=`coder-workspaces`}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 2.2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{namespace=`coder-workspaces`})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2.2 },
   "options": {
    "content": "The cumulative CPU used per core-second. If a workspace was using a full CPU core, that would be represented as 1 second.\n\nSee the Kubernetes [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units) for more details.\n\nThe total memory used by each workspace container is represented; it is the same metric which the [OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) uses."
   }
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10.2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  round(increase(kube_pod_container_status_restarts_total{namespace=`coder-workspaces`}[$__interval]))\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10.2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, reason) (\n  count_over_time(kube_pod_container_status_terminated_reason{namespace=`coder-workspaces`}[$__interval])\n)",
     "legendFormat": "{{pod}}:{{reason}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10.2 },
   "options": {
    "content": "Pods can be terminated for several reasons:\n- `OOMKilled`: pod exceeded its defined memory limit or was terminated by the OS for using excessive memory (if no limit defined)\n- `Error`: usually attributeable to a configuration problem\n- `Evicted`: pod has been evicted from node for overusing resources and will be rescheduled on another node is possible\n\nPod restarts are not necessarily problematic, but they are worth noting."
   }
  },
  { "title": "Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18.2 } },
  {
   "title": "Successful Builds by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_transition) (\n    (\n      # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n      # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n      (\n        coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n        coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n      ) >= 0) \n      or coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful Builds by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_transition) (\n    (\n      # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n      # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n      (\n        coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n        coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n      ) >= 0) \n      or coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19.2 },
   "options": {
    "content": "Workspaces \"transition\" between `STOP`, `START`, and `DESTROY` states.\n\nWorkspaces transition between states when a \"build\" is initiated, which is an execution of `terraform` against the chosen template.\n\nUse the \"Build Count\" table to identify workspace owners which may be struggling with template builds, in order to proactively reach out to them with assistance.\n\nConsult the [Template documentation](https://coder.com/docs/v2/latest/templates) for more information."
   }
  },
  {
   "title": "Build Log",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 27.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_name, workspace_owner, status, template_name, template_version, workspace_transition) (\n  # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n  # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n  ((\n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n  ) >= 0) \n  or coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 27.2 },
   "options": {
    "content": "This table shows a reverse-chronological log of all workspace builds.\n\nThe \"Count\" field shows the count of events which occurred within a minute, grouped by all columns."
   }
  },
  {
   "title": "Workspace by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (workspace_owner) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace by User/Template",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (workspace_owner, template_name) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "{{workspace_owner}}:{{template_name}}"
    }
   ]
  },
  {
   "title": "Template Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (template_name) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Template Version Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (template_name, template_version) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "{{template_name}}:{{template_version}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37.2 },
   "options": {
    "content": "These charts show the distribution of workspaces and templates.\n\nUse these charts to identify which users have outdated templates, and which templates are the most/least popular in your organisation."
   }
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44.2 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 45.2 },
   "targets": [
    {
     "expr": "{namespace=~`(coder|coder)`, logger=~\"(.*runner|terraform|provisioner.*)\"} |~ \"$workspace_name\" or \"$template_name\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 45.2 },
   "options": {
    "content": "These are the logs produced by the [Provisioners](/d/provisionerd/provisioners?${__url_time_range}).\n\nUse the dropdowns at the top to filter the logs down to a specific workspace and/or template."
   }
  }
 ]
}
{
 "title": "Coder Workspace Detail",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "workspace_name",
    "label": "Workspace Name Filter",
    "query": {
     "query": "label_values(coderd_agents_up,workspace_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<small>**HINT**: use the dropdowns above to filter by specific workspace(s).</small>"
   }
  },
  {
   "title": "Details",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (template_name) (coderd_agents_up{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Template Name"
    },
    {
     "expr": "group by (template_version) (coderd_agents_up{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Template Version"
    },
    {
     "expr": "group by (username) (coderd_agents_up{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Owner"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1.2 },
   "options": {
    "content": "Essential information about the selected workspace."
   }
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 5.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*$workspace_name.*\", namespace=`coder-workspaces`, resource=\"cpu\"})",
     "legendFormat": "CPUs Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*$workspace_name.*\", namespace=`coder-workspaces`, resource=\"memory\"})",
     "legendFormat": "RAM Requested"
    },
    {
     "expr": "sum(\n  kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\".*$workspace_name.*\",namespace=`coder-workspaces`}\n  * on(persistentvolumeclaim) group_right\n  group by (persistentvolumeclaim, persistentvolume) (\n      label_replace(\n          kube_persistentvolume_claim_ref,\n          \"persistentvolumeclaim\",\n          \"$1\",\n          \"name\",\n          \"(.+)\"\n      )\n  )\n  * on (persistentvolume)\n  kube_persistentvolume_capacity_bytes\n)",
     "legendFormat": "PVC Capacity"
    }
   ]
  },
  {
   "title": "Agent Lifecycle State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (lifecycle_state) (coderd_agents_connections{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Startup Script Execution Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_agentstats_startup_script_seconds{workspace_name=~\"$workspace_name\"}) or vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Session Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (app) (\n    label_replace(\n        {workspace_name=~\"$workspace_name\", __name__=~\"coderd_agentstats_session_count_.*\"},\n        \"app\",\n        \"$1\",\n        \"__name__\",\n        \"coderd_agentstats_session_count_(.*)\"\n    )\n)>0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_agents_connection_latencies_seconds{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Connection Latency"
    },
    {
     "expr": "max(sum by (pod) (sum_over_time(coderd_agentstats_rx_bytes{workspace_name=~\"$workspace_name\"}[$__range])))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "max(sum by (pod) (sum_over_time(coderd_agentstats_tx_bytes{workspace_name=~\"$workspace_name\"}[$__range])))",
     "legendFormat": "Transmitted Bytes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9.2 },
   "options": {
    "content": "Essential information about this workspace's agent.\n\nRead more about the agent [here](https://coder.com/docs/v2/latest/about/architecture#agents)."
   }
  },
  {
   "title": "Build Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_name, workspace_owner, status, template_name, template_version, workspace_transition) (\n  # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n  # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n  ((\n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\"} - \n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\"} offset $__interval\n  ) >= 0) \n  or coderd_workspace_builds_total{workspace_name=~\"$workspace_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15.2 },
   "options": {
    "content": "This table shows a reverse-chronological log of all workspace builds.\n\nThe \"Count\" field shows the count of events which occurred within a minute, grouped by all columns."
   }
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 22.2 },
   "targets": [
    {
     "expr": "{namespace=~`(coder|coder)`, logger=~\"(.*runner|terraform|provisioner.*)\"} |~ \"$workspace_name\" | line_format `{{ printf \"[\\033[35m\" }}{{.pod}}{{ printf \"\\033[0m]\\t\" }}{{ __line__ }}`"
    },
    {
     "expr": "{namespace=`coder-workspaces`, pod=~\".*($workspace_name).*\"} | line_format `{{ printf \"[\\033[32m\" }}{{.pod}}{{ printf \"\\033[0m]\\t\" }}{{ __line__ }}`"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 22.2 },
   "options": {
    "content": "The logs to the left come both from provisioners and workspace logs.\n\nProvisioner logs matching the name filter are highlighted in <span style=\"color:rgb(204, 0, 204)\">magenta</span>, while\nworkspace logs matching the name filter are highlighted in <span style=\"color:rgb(0, 204, 0)\">green</span>."
   }
  }
 ]
}